### ISSUE TITLE
How to run CGCT instead of D-CGCT?

### ISSUE THREAD

**Issue by FrancescoCappio** [Evgeneus/Graph-Domain-Adaptaion#1]
From my understanding this code by default runs the D-CGCT variant of your method. However I am interested in comparing its performances with a MTDA method I am working on, which does not use domain labels for target samples. What should I do to run D-CGCT? Should I simply put all target data in a single txt file and use it as if it was a single target? 

Thanks in advance

**Comment by Evgeneus** [comment]
Hi @FrancescoCappio! Thanks for your interest! We are planning to release code for CGCT soon.

**Comment by Evgeneus** [comment]
Hi @FrancescoCappio!  Updated the repo with CGCT code!
