### ISSUE TITLE
DomainNet: Accuracy Information

### ISSUE THREAD

**Issue by take2rohit** [Evgeneus/Graph-Domain-Adaptaion#4]
Wanted to know that whether the accuracy reported in the paper is achieved through test split or train split.

|Train | clipart_train.txt | infograph_train.txt | painting_train.txt | quickdraw_train.txt | real_train.txt | sketch_train.txt|
-- | -- | -- | -- | -- | -- | --
| Test | clipart_test.txt | infograph_test.txt | painting_test.txt | quickdraw_test.txt | real_test.txt | sketch_test.txt|

Thanks.

**Comment by roysubhankar** [comment]
Hi @take2rohit , the accuracy for domain net is computed on the test split.

https://github.com/Evgeneus/Graph-Domain-Adaptaion/blob/fc28423d40808c8a92f6135f93add457202f475b/src/utils.py#L152

**Comment by take2rohit** [comment]
Thanks
